### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by ghost** [Trass3r/DevUtils#1]
Please record a little video about the plugin

**Comment by Trass3r** [comment]
Hi there's not that much to show, the main functionality is in the editor context menu:
![image](https://cloud.githubusercontent.com/assets/404623/12788282/3d624232-ca99-11e5-85da-7456970c8fe1.png)

**Comment by ghost** [comment]
Having dealt with the plugin, thank you!

Is it possible to "preprocessed temp file" to compile?

**Comment by Trass3r** [comment]
The preprocessed output should compile.
Assembly output on the other hand can't be fed into masm as-is afaik.

**Comment by ghost** [comment]
fun to try
