### ISSUE TITLE
Does not load correctly in VS2017

### ISSUE THREAD

**Issue by p4654545** [Trass3r/DevUtils#3]
V0.7.0 does not load correctly. It may have been caused by the recent “upgrade to VS2019...” commit, in which case it may be intentional.

**Comment by Trass3r** [comment]
hmm it worked for me. Anything in ActivityLog.xml? It's in %APPDATA% or %LOCALAPPDATA% one.

**Comment by p4654545** [comment]
This is the relevant entry:

<entry>
    <record>783</record>
    <time>2019/05/16 07:51:45.011</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [DevUtilsPackage]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{19B8A882-47F2-4FDD-A657-5F15A2C5ECAE}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo></errorinfo>
  </entry>

**Comment by Trass3r** [comment]
sigh, MS and its versioning. I already suspected that.
Of course I have it in my system because I have both versions installed.
Please try this updated vsix: https://github.com/Trass3r/DevUtils/releases/tag/v0.7.0

**Comment by p4654545** [comment]
That seems to work. Thank you!

**Comment by Trass3r** [comment]
Thanks for reporting it! 👍
I've simply built it with VS2017.
